-- AlterTable
ALTER TABLE "Break" ALTER COLUMN "startTime" SET DATA TYPE VARCHAR,
ALTER COLUMN "endTime" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Shift" ALTER COLUMN "startTime" SET DATA TYPE VARCHAR,
ALTER COLUMN "endTime" SET DATA TYPE VARCHAR;
